# base docker-compose

version: '3.4'

volumes:
  redis: {}

services:
  # this is just here for example
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
    ports:
      - 127.0.0.1:6379:6379

  app:
    restart: always
    build: .
    environment:
      APP_REDIS_URL: redis://redis:6379/0